data_path: ./data/REVERE
output: ./output/REVERE
sal_model: ./models/saliency/mlnet_25.pth
batch_size: 5
image_shape: [1536, 2048]
input_shape: [480, 640]
data_aug: true
frame_interval: 5
step_size: 1
len_clip: 1
rho: 0.97
fusion: "static"  # static or dynamic
fusion_margin: 0.5
score_thresh: 0.5
use_salmap: false  # set to False to speedup data loading
state_norm: true
saliency: 'MLNet'
